---
ID: "b2cb9eb0-79dc-4b42-bbf5-ee1206cf93f8"
Parent: "922dcaf0-24a8-4896-81cf-824c12d0b33f"
Template: "922dcaf0-24a8-4896-81cf-824c12d0b33f"
Path: /sitecore/templates/Modules/DataSync/DataSync Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {0A22B6FB-FCA8-402D-B48B-9D44DE06EC0B}
    {44386FAF-D7C3-4FC4-86A7-5955749CB0AD}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240302T032552Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\james.gregory@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\james.gregory@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0dc505a6-28eb-4335-887d-ffa15924e7a6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\james.gregory@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240302T033424Z
